# Generated by Django 5.0.4 on 2024-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efit', '0002_membership_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Ultimate', 'Ultimate'), ('Premium', 'Premium')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
